version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /test2.txt  
    destination: /var/www/html/
  - source: /test3.txt  
    destination: /var/www/html/
  - source: /test4.txt  
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/remove
      timeout: 300
      runas: root
    - location: scripts/create3
      timeout: 300
      runas: root
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

